module.exports = {
  User: require('./user.model'),
  Team: require('./team.model'),
  JoinRequest: require('./join-request.model'),
  TeamResource: require('./team-resource.model'),
  Course: require('./course.model'),
  Enrollment: require('./enrollment.model'),
  Lesson: require('./lesson.model'),
  LessonProgress: require('./lesson-progress.model'),
  TeamMessage: require('./team-message.model'),
  Material: require('./material.model'),
  Quiz: require('./quiz.model'),
  QuizAttempt: require('./quiz-attempt.model'),
  Assignment: require('./assignment.model'),
  Submission: require('./submission.model'),
  Announcement: require('./announcement.model'),
  Post: require('./post.model'),
  Comment: require('./comment.model'),
  Notification: require('./notification.model'),
};
